### PR TITLE
🚑 critical hotfix : logout bugs

### PR DESCRIPTION
**Pull request by gitaalekhyapaul**
# Description

Logout Handler Bug Fixes

### CODE REVIEW

**Review by sakshi-choudhary — APPROVED** [review]
Thanks✅

**Review by DaemonOnCode — APPROVED** [review]
Finally!

**Review by shvam0000 — APPROVED** [review]
👍🏻

**Review by saxenabhishek — APPROVED** [review]
Looks good 🍇

**Pull request merged**
