### PR TITLE
Version 3.0.0

### PR DESCRIPTION
**Pull request by gitaalekhyapaul**
# Description

## :confetti_ball: Version 3.0.0

- OAuth 2.0
- Admin and Maintainer deletion Routes
- Minor bugs and fixes

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [x] Python Unit Testing
- [x] Python Integration Testing

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented on my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Review by Aradhya-Tripathi — APPROVED** [review]
Looks 🔥

**Review by sakshi-choudhary — APPROVED** [review]
LGTM ❤️🚀

**Review by saxenabhishek — APPROVED** [review]
Seems fine

**Review by jagnani73 — APPROVED** [review]
Great work guys!

**Review by shvam0000 — APPROVED** [review]
LGTM 👍🏻

**Pull request merged**
