### PR TITLE
✨ Final touches

### LINKED ISSUE #117: Error Pages
# Expected Behavior

Add 404 & 500 Error Pages

### LINKED ISSUE #118: Sentry Disable on Dev
# Expected Behavior

Disable Sentry on Dev environment
# Current Behavior

Sentry is always enabled, even on Dev environment

### LINKED ISSUE #119: Rejection Email Templates
# Expected Behavior

Send emails on maintainer and contributor rejection.

# Current Behavior

No emails are being sent as of this issue creation.

### PR DESCRIPTION
**Pull request by shvam0000**
# Description

- 404 ErrorPage
- 500 Error Page
- Disable Sentry on Dev
- Add email templates
- Server boot from test script
- Rejection emails

Fixes #117 
Fixes #118 
Fixes #119 

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented on my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Review by gitaalekhyapaul — DISMISSED** [review]
:+1:

**Review by waterupto — APPROVED** [review]

**Review by gitaalekhyapaul — APPROVED** [review]
:+1:

**Review by saxenabhishek — APPROVED** [review]
LGTM 🍇!

**Review by sakshi-choudhary — APPROVED** [review]
✅

**Pull request merged**
